/**
 * Solid Worlds — the free-action (genuine-manifold) test for a glued cube.
 *
 * ℝ³/Γ is a closed flat *manifold* (one of the ten platycosms) iff the deck
 * group Γ acts **freely** — no nonidentity isometry has a fixed point. The
 * vertex-link = S² test is *not enough*: a rotational cone point (an orbifold
 * singularity from a rotation axis) has a link that is *topologically* a sphere,
 * so a link test silently accepts orbifolds. This module decides freeness
 * group-theoretically with exact integer arithmetic.
 *
 * Work in the cube [0,2]³ (edge length 2) so every translation is an integer
 * vector: a pairing contributes `t = 2·e_axis + 2·offset` (offsets are halves ⇒
 * `2·offset` is integral). Γ is generated by the three face-pairings g_a and
 * their inverses; its point group H = ⟨linear parts⟩ is finite. Each nonidentity
 * h ∈ H is realized by some γ = (h, τ) ∈ Γ; the elements of Γ with linear part h
 * form the single coset τ + L (L = translation lattice). (h, t) has a fixed
 * point iff t ∈ im(I−h), so the action is free iff for every h ≠ I the coset
 * τ + L misses im(I−h), i.e. τ ∉ im(I−h) + L. Writing C for an integer basis of
 * the left null space of (I−h) (the cokernel functionals, which annihilate
 * im(I−h)), that is: **no integer n solves (C·L)·n = C·τ**. We get L by the
 * Reidemeister–Schreier construction and decide the integer system by Smith-form
 * row reduction.
 */

import { M3, SolidWorldSpec, axisIndex, transposeM3 } from '../solidSchema';

type Vec = [number, number, number];
interface Aff { M: M3; t: Vec } // integer affine isometry v ↦ M·v + t on [0,2]³

const mulMM = (a: M3, b: M3): M3 => {
  const r = new Array(9).fill(0);
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) { let s = 0; for (let k = 0; k < 3; k++) s += a[i * 3 + k] * b[k * 3 + j]; r[i * 3 + j] = s; }
  return r;
};
const applyMv = (m: M3, v: Vec): Vec => [
  m[0] * v[0] + m[1] * v[1] + m[2] * v[2],
  m[3] * v[0] + m[4] * v[1] + m[5] * v[2],
  m[6] * v[0] + m[7] * v[1] + m[8] * v[2],
];
const compose = (a: Aff, b: Aff): Aff => ({ M: mulMM(a.M, b.M), t: addv(applyMv(a.M, b.t), a.t) });
const invAff = (a: Aff): Aff => { const Mi = transposeM3(a.M); return { M: Mi, t: applyMv(Mi, a.t).map((x) => -x) as Vec }; };
const addv = (a: Vec, b: Vec): Vec => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const dot = (a: number[], b: number[]): number => a.reduce((s, x, i) => s + x * b[i], 0);
const keyM = (m: M3): string => m.join(',');
const ID: M3 = [1, 0, 0, 0, 1, 0, 0, 0, 1];

function generators(spec: SolidWorldSpec): Aff[] {
  const gs: Aff[] = [];
  for (const p of spec.pairings) {
    const a = axisIndex(p.axis);
    const t: Vec = [0, 0, 0]; t[a] = 2;
    if (p.offset) { t[0] += p.offset[0] * 2; t[1] += p.offset[1] * 2; t[2] += p.offset[2] * 2; }
    gs.push({ M: p.linear, t });
  }
  return gs;
}

/** Point group H and a transversal: one Γ-element `rep[h]` per h ∈ H. */
function pointGroup(gens: Aff[]): Map<string, Aff> {
  const all = [...gens, ...gens.map(invAff)];
  const rep = new Map<string, Aff>([[keyM(ID), { M: ID, t: [0, 0, 0] }]]);
  const queue: Aff[] = [{ M: ID, t: [0, 0, 0] }];
  while (queue.length) {
    const r = queue.shift()!;
    for (const s of all) {
      const rs = compose(s, r); const k = keyM(rs.M);
      if (!rep.has(k)) { rep.set(k, rs); queue.push(rs); }
    }
  }
  return rep;
}

/** A generating set of the translation lattice L (Reidemeister–Schreier). */
function latticeGens(gens: Aff[], rep: Map<string, Aff>): Vec[] {
  const all = [...gens, ...gens.map(invAff)];
  const out: Vec[] = [];
  for (const r of rep.values()) for (const s of all) {
    const rs = compose(r, s);
    const back = rep.get(keyM(rs.M))!;     // coset representative of r·s
    const sg = compose(rs, invAff(back));  // ∈ L (linear part I)
    if (sg.t[0] || sg.t[1] || sg.t[2]) out.push(sg.t);
  }
  return out;
}

/** Integer basis of the left null space of M (rows w with wᵀM = 0), primitivized. */
function leftNull(M: M3): Vec[] {
  // rational null space of Mᵀ; rows of the basis cleared to primitive integers.
  const A = [transposeM3(M).slice(0, 3), transposeM3(M).slice(3, 6), transposeM3(M).slice(6, 9)].map((r) => r.map(Number));
  // Gaussian elimination over rationals on Aᵀ? We want { w : Mᵀ w = 0 } = null(Mᵀ).
  return rationalNullspace(A);
}

/** Null space basis of a 3×3 integer matrix, as primitive integer vectors. */
function rationalNullspace(A: number[][]): Vec[] {
  const m = A.map((r) => r.map((x) => x)); // rational copy
  const n = 3;
  const pivotCol: number[] = []; let row = 0;
  for (let col = 0; col < n && row < n; col++) {
    let piv = -1; for (let i = row; i < n; i++) if (Math.abs(m[i][col]) > 1e-9) { piv = i; break; }
    if (piv === -1) continue;
    [m[row], m[piv]] = [m[piv], m[row]];
    const p = m[row][col];
    for (let j = 0; j < n; j++) m[row][j] /= p;
    for (let i = 0; i < n; i++) if (i !== row) { const f = m[i][col]; for (let j = 0; j < n; j++) m[i][j] -= f * m[row][j]; }
    pivotCol.push(col); row++;
  }
  const isPivot = new Set(pivotCol);
  const free: number[] = []; for (let c = 0; c < n; c++) if (!isPivot.has(c)) free.push(c);
  const basis: Vec[] = [];
  for (const fc of free) {
    const v = [0, 0, 0]; v[fc] = 1;
    for (let i = 0; i < pivotCol.length; i++) v[pivotCol[i]] = -m[i][fc];
    basis.push(primitive(v as Vec));
  }
  return basis;
}

function primitive(v: Vec): Vec {
  // scale to integers (denominators are small powers of the pivots) then divide by gcd
  let scale = 1;
  for (const x of v) { const d = denom(x); scale = lcm(scale, d); }
  const w = v.map((x) => Math.round(x * scale)) as Vec;
  let g = 0; for (const x of w) g = gcd(g, x);
  if (g > 1) for (let i = 0; i < 3; i++) w[i] /= g;
  // canonical sign
  for (const x of w) if (x !== 0) { if (x < 0) for (let i = 0; i < 3; i++) w[i] = -w[i]; break; }
  return w;
}
const denom = (x: number, max = 5040): number => { for (let d = 1; d <= max; d++) if (Math.abs(x * d - Math.round(x * d)) < 1e-6) return d; return 1; };
const gcd = (a: number, b: number): number => { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a; };
const lcm = (a: number, b: number): number => (a && b ? Math.abs(a * b) / gcd(a, b) : a || b);

/** Does A·n = b have an integer solution? (Smith-form row reduction; column
 *  operations permute the unknowns, row operations are mirrored on b.) */
function integerSolvable(A: number[][], b: number[]): boolean {
  const M = A.map((r) => r.slice()); const rhs = b.slice();
  const rows = M.length, cols = rows ? M[0].length : 0;
  let r = 0, c = 0; const diag: number[] = [];
  while (r < rows && c < cols) {
    let cleared = false;
    while (!cleared) {
      let pi = -1, pj = -1, best = Infinity;
      for (let i = r; i < rows; i++) for (let j = c; j < cols; j++) { const v = Math.abs(M[i][j]); if (v !== 0 && v < best) { best = v; pi = i; pj = j; } }
      if (pi === -1) break;
      [M[r], M[pi]] = [M[pi], M[r]]; [rhs[r], rhs[pi]] = [rhs[pi], rhs[r]];     // row swap (b too)
      for (let i = 0; i < rows; i++) { const tmp = M[i][c]; M[i][c] = M[i][pj]; M[i][pj] = tmp; } // col swap
      for (let i = r + 1; i < rows; i++) {
        if (M[i][c] === 0) continue;
        const q = Math.round(M[i][c] / M[r][c]);
        if (q !== 0) { for (let j = c; j < cols; j++) M[i][j] -= q * M[r][j]; rhs[i] -= q * rhs[r]; }
      }
      for (let j = c + 1; j < cols; j++) {
        if (M[r][j] === 0) continue;
        const q = Math.round(M[r][j] / M[r][c]);
        if (q !== 0) for (let i = r; i < rows; i++) M[i][j] -= q * M[i][c];
      }
      cleared = true;
      for (let i = r + 1; i < rows; i++) if (M[i][c] !== 0) cleared = false;
      for (let j = c + 1; j < cols; j++) if (M[r][j] !== 0) cleared = false;
    }
    if (M[r][c] === 0) break;
    diag.push(M[r][c]); r++; c++;
  }
  for (let i = 0; i < diag.length; i++) if (rhs[i] % diag[i] !== 0) return false; // pivot row: divisibility
  for (let i = diag.length; i < rows; i++) if (rhs[i] !== 0) return false;          // zero row: consistency
  return true;
}

/** True iff the deck group acts freely — i.e. ℝ³/Γ is a genuine flat manifold
 *  (a platycosm), not an orbifold with cone/mirror singularities. */
export function isFreeAction(spec: SolidWorldSpec): boolean {
  const gens = generators(spec);
  const rep = pointGroup(gens);
  const L = latticeGens(gens, rep);
  for (const [k, r] of rep) {
    if (k === keyM(ID)) continue;
    const B: M3 = ID.map((v, i) => v - r.M[i]); // I − h
    const C = leftNull(B);                       // annihilators of im(I−h)
    if (C.length === 0) return false;            // im(I−h)=ℝ³ ⇒ a fixed point always exists
    const A = C.map((w) => L.map((l) => dot(w, l)));
    const bvec = C.map((w) => dot(w, r.t));
    if (integerSolvable(A, bvec)) return false;  // the coset meets im(I−h) ⇒ a fixed point
  }
  return true;
}

// ── independent H₁ = Γᵃᵇ (Bieberbach abelianization) ─────────────────────────
// A genuinely independent cross-check on the cell-complex homology: no cube
// cells, no boundary maps. Γ is generated by g_x, g_y, g_z, so Γᵃᵇ = ℤ³ / R.
// Every conjugation g_a ℓ g_a⁻¹ = (M_a·ℓ) of a translation ℓ ∈ L gives, in the
// abelianization, [ℓ] = [M_a·ℓ]; and every generator order g_a^{ord(M_a)} = a
// translation gives ord·[g_a] = [that translation]. Expressing translations as
// integer words in the generators (carried through the point-group BFS and the
// Reidemeister–Schreier lattice) turns all of those into integer relations among
// [g_x],[g_y],[g_z]; the Smith form of the relation matrix is Γᵃᵇ.

interface AffW { aff: Aff; word: Vec } // affine + abelianized word (counts of g_x,g_y,g_z)

function pointGroupW(gens: Aff[]): Map<string, AffW> {
  const labeled: { aff: Aff; word: Vec }[] = [];
  gens.forEach((g, a) => { const w: Vec = [0, 0, 0]; w[a] = 1; labeled.push({ aff: g, word: w }); });
  gens.forEach((g, a) => { const w: Vec = [0, 0, 0]; w[a] = -1; labeled.push({ aff: invAff(g), word: w }); });
  const rep = new Map<string, AffW>([[keyM(ID), { aff: { M: ID, t: [0, 0, 0] }, word: [0, 0, 0] }]]);
  const queue: AffW[] = [rep.get(keyM(ID))!];
  while (queue.length) {
    const r = queue.shift()!;
    for (const s of labeled) {
      const aff = compose(s.aff, r.aff); const k = keyM(aff.M);
      if (!rep.has(k)) { const e: AffW = { aff, word: addv(s.word, r.word) }; rep.set(k, e); queue.push(e); }
    }
  }
  return rep;
}

/** Lattice elements as (translation vector, abelianized word). */
function latticeGensW(gens: Aff[], rep: Map<string, AffW>): { v: Vec; w: Vec }[] {
  const labeled: { aff: Aff; word: Vec }[] = [];
  gens.forEach((g, a) => { const w: Vec = [0, 0, 0]; w[a] = 1; labeled.push({ aff: g, word: w }); });
  gens.forEach((g, a) => { const w: Vec = [0, 0, 0]; w[a] = -1; labeled.push({ aff: invAff(g), word: w }); });
  const out: { v: Vec; w: Vec }[] = [];
  for (const r of rep.values()) for (const s of labeled) {
    const rs = compose(r.aff, s.aff);
    const back = rep.get(keyM(rs.M))!;            // coset rep of r·s
    const sg = compose(rs, invAff(back.aff));     // ∈ L
    const word = addv(addv(r.word, s.word), back.word.map((x) => -x) as Vec);
    if (sg.t[0] || sg.t[1] || sg.t[2] || word[0] || word[1] || word[2]) out.push({ v: sg.t, w: word });
  }
  return out;
}

/** A ℤ-basis of the lattice (Hermite reduction on the vector part, carrying the
 *  word part), plus integer coordinates of any lattice vector in that basis. */
function latticeBasisW(gens: { v: Vec; w: Vec }[]): { basis: { v: Vec; w: Vec }[]; coords: (q: Vec) => number[] } {
  const rows = gens.map((g) => [...g.v, ...g.w]); // [vx,vy,vz, wx,wy,wz]
  let r = 0;
  for (let col = 0; col < 3 && r < rows.length; col++) {
    // bring the smallest nonzero in `col` to position r, reduce all others; the
    // pivot is re-selected each round so a residue can't stall the loop.
    let done = false;
    while (!done) {
      let piv = -1, best = Infinity;
      for (let i = r; i < rows.length; i++) if (rows[i][col] !== 0 && Math.abs(rows[i][col]) < best) { best = Math.abs(rows[i][col]); piv = i; }
      if (piv === -1) break;
      [rows[r], rows[piv]] = [rows[piv], rows[r]];
      done = true;
      for (let i = r + 1; i < rows.length; i++) {
        if (rows[i][col] === 0) continue;
        const q = Math.round(rows[i][col] / rows[r][col]);
        if (q !== 0) for (let j = 0; j < 6; j++) rows[i][j] -= q * rows[r][j];
        if (rows[i][col] !== 0) done = false; // a smaller residue ⇒ re-pivot next round
      }
    }
    if (r < rows.length && rows[r][col] !== 0) r++;
  }
  const basis = rows.slice(0, r).map((row) => ({ v: row.slice(0, 3) as Vec, w: row.slice(3, 6) as Vec }));
  const B = basis.map((b) => b.v);
  const coords = (q: Vec): number[] => {
    // solve Σ c_i B[i] = q (B upper-triangular-ish from the reduction); integer
    const c = new Array(B.length).fill(0); const rem: Vec = [...q];
    for (let i = 0; i < B.length; i++) {
      const lead = B[i].findIndex((x) => x !== 0);
      if (lead === -1) continue;
      const ci = Math.round(rem[lead] / B[i][lead]); c[i] = ci;
      for (let j = 0; j < 3; j++) rem[j] -= ci * B[i][j];
    }
    return c;
  };
  return { basis, coords };
}

function smithFactors(mat: number[][]): { rank: number; factors: number[] } {
  const A = mat.map((r) => r.slice());
  const rows = A.length, cols = rows ? A[0].length : 0;
  const ds: number[] = []; let r = 0, c = 0;
  while (r < rows && c < cols) {
    let cleared = false;
    while (!cleared) {
      let pi = -1, pj = -1, best = Infinity;
      for (let i = r; i < rows; i++) for (let j = c; j < cols; j++) { const v = Math.abs(A[i][j]); if (v !== 0 && v < best) { best = v; pi = i; pj = j; } }
      if (pi === -1) break;
      [A[r], A[pi]] = [A[pi], A[r]];
      for (let i = 0; i < rows; i++) { const t = A[i][c]; A[i][c] = A[i][pj]; A[i][pj] = t; }
      for (let i = r + 1; i < rows; i++) { if (A[i][c] === 0) continue; const q = Math.round(A[i][c] / A[r][c]); if (q) for (let j = c; j < cols; j++) A[i][j] -= q * A[r][j]; }
      for (let j = c + 1; j < cols; j++) { if (A[r][j] === 0) continue; const q = Math.round(A[r][j] / A[r][c]); if (q) for (let i = r; i < rows; i++) A[i][j] -= q * A[i][c]; }
      cleared = true;
      for (let i = r + 1; i < rows; i++) if (A[i][c] !== 0) cleared = false;
      for (let j = c + 1; j < cols; j++) if (A[r][j] !== 0) cleared = false;
    }
    if (A[r][c] === 0) break;
    ds.push(Math.abs(A[r][c])); r++; c++;
  }
  let changed = true;
  while (changed) { changed = false; for (let i = 0; i < ds.length; i++) for (let j = i + 1; j < ds.length; j++) { const g = gcd(ds[i], ds[j]); if (g !== ds[i]) { const l = (ds[i] / g) * ds[j]; ds[i] = g; ds[j] = l; changed = true; } } }
  return { rank: ds.length, factors: ds };
}

/** H₁ = Γᵃᵇ via the group abelianization — independent of the cube cell complex. */
export function abelianizationH1(spec: SolidWorldSpec): { rank: number; torsion: number[]; h1: string } {
  const gens = generators(spec);
  const rep = pointGroupW(gens);
  const latGens = latticeGensW(gens, rep);
  const { basis, coords } = latticeBasisW(latGens);
  const rels: Vec[] = []; // each relation is a ℤ-vector in [a_x, a_y, a_z]
  // word of a lattice vector = Σ coords_i · (basis word)_i
  const wordOf = (q: Vec): Vec => {
    const c = coords(q); const w: Vec = [0, 0, 0];
    c.forEach((ci, i) => { w[0] += ci * basis[i].w[0]; w[1] += ci * basis[i].w[1]; w[2] += ci * basis[i].w[2]; });
    return w;
  };
  // consistency: every lattice element written two ways (its Reidemeister–Schreier
  // word vs. its decomposition in the chosen basis) must agree in Γᵃᵇ. These are
  // the relators that the point-group relations impose — including the
  // commutators of two rotation generators (the multi-rotation hol-4 cases).
  for (const g of latGens) rels.push(addv(g.w, wordOf(g.v).map((x) => -x) as Vec));
  // conjugation: [b_i] − [M_a·b_i] = 0 for each basis element and generator
  for (let a = 0; a < 3; a++) for (const b of basis) {
    const img = applyMv(gens[a].M, b.v);              // M_a · b  (a lattice vector)
    rels.push(addv(b.w, wordOf(img).map((x) => -x) as Vec));
  }
  // generator order: ord(M_a)·[g_a] − [g_a^{ord}] = 0  (g_a^{ord} is a translation)
  for (let a = 0; a < 3; a++) {
    let pw: Aff = { M: ID, t: [0, 0, 0] }; let ord = 0;
    do { pw = compose(pw, gens[a]); ord++; } while (keyM(pw.M) !== keyM(ID) && ord < 24);
    const ea: Vec = [0, 0, 0]; ea[a] = ord;
    rels.push(addv(ea, wordOf(pw.t).map((x) => -x) as Vec));
  }
  const mat = rels.length ? rels : [[0, 0, 0]];
  const { rank: relRank, factors } = smithFactors(mat);
  const rank = 3 - relRank;
  const torsion = factors.filter((d) => d > 1);
  return { rank, torsion, h1: formatH1ab(rank, torsion) };
}

function formatH1ab(rank: number, torsion: number[]): string {
  const sup = (n: number) => String(n).split('').map((c) => '⁰¹²³⁴⁵⁶⁷⁸⁹'[+c]).join('');
  const parts: string[] = [];
  if (rank === 1) parts.push('ℤ'); else if (rank > 1) parts.push(`ℤ${sup(rank)}`);
  for (const d of torsion) parts.push(`ℤ/${d}`);
  return parts.length ? parts.join(' ⊕ ') : '0';
}
