/**
 * Solid Worlds — the free-action (genuine-manifold) test for a glued cube.
 *
 * ℝ³/Γ is a closed flat *manifold* (one of the ten platycosms) iff the deck
 * group Γ acts **freely** — no nonidentity isometry has a fixed point. The
 * vertex-link = S² test is *not enough*: a rotational cone point (an orbifold
 * singularity from a rotation axis) has a link that is *topologically* a sphere,
 * so a link test silently accepts orbifolds. This module decides freeness
 * group-theoretically with exact integer arithmetic.
 *
 * Work in the cube [0,2]³ (edge length 2) so every translation is an integer
 * vector: a pairing contributes `t = 2·e_axis + 2·offset` (offsets are halves ⇒
 * `2·offset` is integral). Γ is generated by the three face-pairings g_a and
 * their inverses; its point group H = ⟨linear parts⟩ is finite. Each nonidentity
 * h ∈ H is realized by some γ = (h, τ) ∈ Γ; the elements of Γ with linear part h
 * form the single coset τ + L (L = translation lattice). (h, t) has a fixed
 * point iff t ∈ im(I−h), so the action is free iff for every h ≠ I the coset
 * τ + L misses im(I−h), i.e. τ ∉ im(I−h) + L. Writing C for an integer basis of
 * the left null space of (I−h) (the cokernel functionals, which annihilate
 * im(I−h)), that is: **no integer n solves (C·L)·n = C·τ**. We get L by the
 * Reidemeister–Schreier construction and decide the integer system by Smith-form
 * row reduction.
 */

import { M3, SolidWorldSpec, axisIndex, transposeM3 } from '../solidSchema';

type Vec = [number, number, number];
interface Aff { M: M3; t: Vec } // integer affine isometry v ↦ M·v + t on [0,2]³

const mulMM = (a: M3, b: M3): M3 => {
  const r = new Array(9).fill(0);
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) { let s = 0; for (let k = 0; k < 3; k++) s += a[i * 3 + k] * b[k * 3 + j]; r[i * 3 + j] = s; }
  return r;
};
const applyMv = (m: M3, v: Vec): Vec => [
  m[0] * v[0] + m[1] * v[1] + m[2] * v[2],
  m[3] * v[0] + m[4] * v[1] + m[5] * v[2],
  m[6] * v[0] + m[7] * v[1] + m[8] * v[2],
];
const compose = (a: Aff, b: Aff): Aff => ({ M: mulMM(a.M, b.M), t: addv(applyMv(a.M, b.t), a.t) });
const invAff = (a: Aff): Aff => { const Mi = transposeM3(a.M); return { M: Mi, t: applyMv(Mi, a.t).map((x) => -x) as Vec }; };
const addv = (a: Vec, b: Vec): Vec => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const dot = (a: number[], b: number[]): number => a.reduce((s, x, i) => s + x * b[i], 0);
const keyM = (m: M3): string => m.join(',');
const ID: M3 = [1, 0, 0, 0, 1, 0, 0, 0, 1];

function generators(spec: SolidWorldSpec): Aff[] {
  const gs: Aff[] = [];
  for (const p of spec.pairings) {
    const a = axisIndex(p.axis);
    const t: Vec = [0, 0, 0]; t[a] = 2;
    if (p.offset) { t[0] += p.offset[0] * 2; t[1] += p.offset[1] * 2; t[2] += p.offset[2] * 2; }
    gs.push({ M: p.linear, t });
  }
  return gs;
}

/** Point group H and a transversal: one Γ-element `rep[h]` per h ∈ H. */
function pointGroup(gens: Aff[]): Map<string, Aff> {
  const all = [...gens, ...gens.map(invAff)];
  const rep = new Map<string, Aff>([[keyM(ID), { M: ID, t: [0, 0, 0] }]]);
  const queue: Aff[] = [{ M: ID, t: [0, 0, 0] }];
  while (queue.length) {
    const r = queue.shift()!;
    for (const s of all) {
      const rs = compose(s, r); const k = keyM(rs.M);
      if (!rep.has(k)) { rep.set(k, rs); queue.push(rs); }
    }
  }
  return rep;
}

/** A generating set of the translation lattice L (Reidemeister–Schreier). */
function latticeGens(gens: Aff[], rep: Map<string, Aff>): Vec[] {
  const all = [...gens, ...gens.map(invAff)];
  const out: Vec[] = [];
  for (const r of rep.values()) for (const s of all) {
    const rs = compose(r, s);
    const back = rep.get(keyM(rs.M))!;     // coset representative of r·s
    const sg = compose(rs, invAff(back));  // ∈ L (linear part I)
    if (sg.t[0] || sg.t[1] || sg.t[2]) out.push(sg.t);
  }
  return out;
}

/** Integer basis of the left null space of M (rows w with wᵀM = 0), primitivized. */
function leftNull(M: M3): Vec[] {
  // rational null space of Mᵀ; rows of the basis cleared to primitive integers.
  const A = [transposeM3(M).slice(0, 3), transposeM3(M).slice(3, 6), transposeM3(M).slice(6, 9)].map((r) => r.map(Number));
  // Gaussian elimination over rationals on Aᵀ? We want { w : Mᵀ w = 0 } = null(Mᵀ).
  return rationalNullspace(A);
}

/** Null space basis of a 3×3 integer matrix, as primitive integer vectors. */
function rationalNullspace(A: number[][]): Vec[] {
  const m = A.map((r) => r.map((x) => x)); // rational copy
  const n = 3;
  const pivotCol: number[] = []; let row = 0;
  for (let col = 0; col < n && row < n; col++) {
    let piv = -1; for (let i = row; i < n; i++) if (Math.abs(m[i][col]) > 1e-9) { piv = i; break; }
    if (piv === -1) continue;
    [m[row], m[piv]] = [m[piv], m[row]];
    const p = m[row][col];
    for (let j = 0; j < n; j++) m[row][j] /= p;
    for (let i = 0; i < n; i++) if (i !== row) { const f = m[i][col]; for (let j = 0; j < n; j++) m[i][j] -= f * m[row][j]; }
    pivotCol.push(col); row++;
  }
  const isPivot = new Set(pivotCol);
  const free: number[] = []; for (let c = 0; c < n; c++) if (!isPivot.has(c)) free.push(c);
  const basis: Vec[] = [];
  for (const fc of free) {
    const v = [0, 0, 0]; v[fc] = 1;
    for (let i = 0; i < pivotCol.length; i++) v[pivotCol[i]] = -m[i][fc];
    basis.push(primitive(v as Vec));
  }
  return basis;
}

function primitive(v: Vec): Vec {
  // scale to integers (denominators are small powers of the pivots) then divide by gcd
  let scale = 1;
  for (const x of v) { const d = denom(x); scale = lcm(scale, d); }
  const w = v.map((x) => Math.round(x * scale)) as Vec;
  let g = 0; for (const x of w) g = gcd(g, x);
  if (g > 1) for (let i = 0; i < 3; i++) w[i] /= g;
  // canonical sign
  for (const x of w) if (x !== 0) { if (x < 0) for (let i = 0; i < 3; i++) w[i] = -w[i]; break; }
  return w;
}
const denom = (x: number, max = 5040): number => { for (let d = 1; d <= max; d++) if (Math.abs(x * d - Math.round(x * d)) < 1e-6) return d; return 1; };
const gcd = (a: number, b: number): number => { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a; };
const lcm = (a: number, b: number): number => (a && b ? Math.abs(a * b) / gcd(a, b) : a || b);

/** Does A·n = b have an integer solution? (Smith-form row reduction; column
 *  operations permute the unknowns, row operations are mirrored on b.) */
function integerSolvable(A: number[][], b: number[]): boolean {
  const M = A.map((r) => r.slice()); const rhs = b.slice();
  const rows = M.length, cols = rows ? M[0].length : 0;
  let r = 0, c = 0; const diag: number[] = [];
  while (r < rows && c < cols) {
    let cleared = false;
    while (!cleared) {
      let pi = -1, pj = -1, best = Infinity;
      for (let i = r; i < rows; i++) for (let j = c; j < cols; j++) { const v = Math.abs(M[i][j]); if (v !== 0 && v < best) { best = v; pi = i; pj = j; } }
      if (pi === -1) break;
      [M[r], M[pi]] = [M[pi], M[r]]; [rhs[r], rhs[pi]] = [rhs[pi], rhs[r]];     // row swap (b too)
      for (let i = 0; i < rows; i++) { const tmp = M[i][c]; M[i][c] = M[i][pj]; M[i][pj] = tmp; } // col swap
      for (let i = r + 1; i < rows; i++) {
        if (M[i][c] === 0) continue;
        const q = Math.round(M[i][c] / M[r][c]);
        if (q !== 0) { for (let j = c; j < cols; j++) M[i][j] -= q * M[r][j]; rhs[i] -= q * rhs[r]; }
      }
      for (let j = c + 1; j < cols; j++) {
        if (M[r][j] === 0) continue;
        const q = Math.round(M[r][j] / M[r][c]);
        if (q !== 0) for (let i = r; i < rows; i++) M[i][j] -= q * M[i][c];
      }
      cleared = true;
      for (let i = r + 1; i < rows; i++) if (M[i][c] !== 0) cleared = false;
      for (let j = c + 1; j < cols; j++) if (M[r][j] !== 0) cleared = false;
    }
    if (M[r][c] === 0) break;
    diag.push(M[r][c]); r++; c++;
  }
  for (let i = 0; i < diag.length; i++) if (rhs[i] % diag[i] !== 0) return false; // pivot row: divisibility
  for (let i = diag.length; i < rows; i++) if (rhs[i] !== 0) return false;          // zero row: consistency
  return true;
}

/** True iff the deck group acts freely — i.e. ℝ³/Γ is a genuine flat manifold
 *  (a platycosm), not an orbifold with cone/mirror singularities. */
export function isFreeAction(spec: SolidWorldSpec): boolean {
  const gens = generators(spec);
  const rep = pointGroup(gens);
  const L = latticeGens(gens, rep);
  for (const [k, r] of rep) {
    if (k === keyM(ID)) continue;
    const B: M3 = ID.map((v, i) => v - r.M[i]); // I − h
    const C = leftNull(B);                       // annihilators of im(I−h)
    if (C.length === 0) return false;            // im(I−h)=ℝ³ ⇒ a fixed point always exists
    const A = C.map((w) => L.map((l) => dot(w, l)));
    const bvec = C.map((w) => dot(w, r.t));
    if (integerSolvable(A, bvec)) return false;  // the coset meets im(I−h) ⇒ a fixed point
  }
  return true;
}
