/**
 * Solid Worlds — H₁, the Euler characteristic, and a vertex-link manifold
 * certificate from the cellular chain complex of a glued cube (pure integer
 * linear algebra, Three.js-free).
 *
 * The old version hard-coded one CW structure — 8 cube vertices, 12 edges, three
 * opposite-face *pairs* as the 2-cells, one 3-cell — and identified boundary
 * cells by clamping each glued image back to a corner of the *same* cube. That is
 * only valid when each face glues onto the whole opposite face. A **screw** (a
 * perpendicular `Pairing.offset`, needed for Hantzsche–Wendt and the
 * amphidicosms) *staggers* the faces: the image of a face lands shifted within
 * the opposite plane, straddling two neighbor cells, so the whole-face model is
 * false and the old lookup crashes.
 *
 * This version is gluing-agnostic. We subdivide the cube into an N×N×N grid of
 * unit cells (N chosen so every offset is an integer count of sub-edges; N = 1
 * reproduces the old complex exactly for the offset-free worlds). The cube is a
 * fundamental domain for the deck group Γ generated by the three face-pairings;
 * we identify boundary cells by **applying the pairing and then reducing the
 * image back into the cube by greedy face-crossing** (compose generators until
 * every coordinate is in range). That reduction composes the staggered
 * side-pairings automatically. Integer boundary maps ∂₁ (edges→vertices) and ∂₂
 * (faces→edges) then give
 *
 *     rank H₁ = (#edge-classes) − rank ∂₁ − rank ∂₂
 *     torsion H₁ = the invariant factors > 1 of ∂₂
 *
 * with χ = V − E + F − C (= 0 for a closed 3-manifold for any CW structure), and
 * the vertex links certify manifold-ness (each link must be an S²). The sign
 * logic is self-checked by asserting ∂₂∘∂₁ = 0 before reading homology.
 */

import { M3, SolidWorldSpec, axisIndex, transposeM3 } from '../solidSchema';

type V3 = [number, number, number];

const EDGE_LEN = 2; // the cube spans [−1, 1] on each axis

const applyM3 = (m: M3, v: V3): V3 => [
  m[0] * v[0] + m[1] * v[1] + m[2] * v[2],
  m[3] * v[0] + m[4] * v[1] + m[5] * v[2],
  m[6] * v[0] + m[7] * v[1] + m[8] * v[2],
];

// ── union-find (vertices) and signed union-find (oriented edges/faces) ───────
class UF {
  parent: number[];
  constructor(n: number) { this.parent = [...Array(n).keys()]; }
  find(i: number): number { return this.parent[i] === i ? i : (this.parent[i] = this.find(this.parent[i])); }
  union(i: number, j: number) { this.parent[this.find(i)] = this.find(j); }
}

class SignedUF {
  parent: number[]; sign: number[];
  constructor(n: number) { this.parent = [...Array(n).keys()]; this.sign = new Array(n).fill(1); }
  find(i: number): { root: number; sign: number } {
    if (this.parent[i] === i) return { root: i, sign: 1 };
    const r = this.find(this.parent[i]);
    this.parent[i] = r.root; this.sign[i] = this.sign[i] * r.sign;
    return { root: r.root, sign: this.sign[i] };
  }
  union(i: number, j: number, rel: number) { // item i = rel · item j
    const a = this.find(i), b = this.find(j);
    if (a.root === b.root) return;
    this.parent[a.root] = b.root;
    this.sign[a.root] = a.sign * rel * b.sign;
  }
}

const gcd = (a: number, b: number): number => { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a; };

/** Smith normal form (diagonalize by integer row/col ops); returns the nonzero
 *  diagonal entries as canonical invariant factors (d₁ | d₂ | …). The pivot is
 *  re-selected as the smallest remaining nonzero each round, so a reduction that
 *  leaves a residue smaller than the pivot can't stall (the Euclidean step keeps
 *  shrinking the pivot until the row/column clears). */
function smith(mat: number[][]): number[] {
  const A = mat.map((r) => r.slice());
  const rows = A.length, cols = rows ? A[0].length : 0;
  const ds: number[] = [];
  let r = 0, c = 0;
  while (r < rows && c < cols) {
    let cleared = false;
    while (!cleared) {
      // smallest absolute nonzero in the active submatrix becomes the pivot
      let pi = -1, pj = -1, best = Infinity;
      for (let i = r; i < rows; i++) for (let j = c; j < cols; j++) {
        const v = Math.abs(A[i][j]); if (v !== 0 && v < best) { best = v; pi = i; pj = j; }
      }
      if (pi === -1) break; // submatrix is all zero (A[r][c] stays 0 ⇒ loop ends)
      [A[r], A[pi]] = [A[pi], A[r]];
      for (let i = 0; i < rows; i++) { const tmp = A[i][c]; A[i][c] = A[i][pj]; A[i][pj] = tmp; }
      for (let i = r + 1; i < rows; i++) {
        if (A[i][c] === 0) continue;
        const q = Math.round(A[i][c] / A[r][c]);
        if (q !== 0) for (let j = c; j < cols; j++) A[i][j] -= q * A[r][j];
      }
      for (let j = c + 1; j < cols; j++) {
        if (A[r][j] === 0) continue;
        const q = Math.round(A[r][j] / A[r][c]);
        if (q !== 0) for (let i = r; i < rows; i++) A[i][j] -= q * A[i][c];
      }
      cleared = true;
      for (let i = r + 1; i < rows; i++) if (A[i][c] !== 0) cleared = false;
      for (let j = c + 1; j < cols; j++) if (A[r][j] !== 0) cleared = false;
    }
    if (r < rows && c < cols && A[r][c] !== 0) ds.push(Math.abs(A[r][c]));
    else break;
    r++; c++;
  }
  // enforce the divisibility chain → canonical invariant factors
  let changed = true;
  while (changed) {
    changed = false;
    for (let i = 0; i < ds.length; i++) for (let j = i + 1; j < ds.length; j++) {
      const g = gcd(ds[i], ds[j]);
      if (g !== ds[i]) { const l = (ds[i] / g) * ds[j]; ds[i] = g; ds[j] = l; changed = true; }
    }
  }
  return ds;
}

// ── deck generators (one affine isometry per axis, plus its inverse) ─────────
interface Gen { M: M3; t: V3 } // g(v) = M·v + t, in world coordinates

function buildGens(spec: SolidWorldSpec): { fwd: Gen[]; inv: Gen[] } {
  const fwd: Gen[] = [0, 1, 2].map(() => ({ M: [], t: [0, 0, 0] }));
  const inv: Gen[] = [0, 1, 2].map(() => ({ M: [], t: [0, 0, 0] }));
  for (const p of spec.pairings) {
    const a = axisIndex(p.axis);
    const t: V3 = [0, 0, 0];
    t[a] += EDGE_LEN; // the full step along the axis glues −face onto +face
    if (p.offset) { t[0] += p.offset[0] * EDGE_LEN; t[1] += p.offset[1] * EDGE_LEN; t[2] += p.offset[2] * EDGE_LEN; }
    const Mi = transposeM3(p.linear); // orthogonal ⇒ inverse is the transpose
    const ti = applyM3(Mi, t).map((x) => -x) as V3; // g⁻¹(v) = Mᵀ·v − Mᵀ·t
    fwd[a] = { M: p.linear, t };
    inv[a] = { M: Mi, t: ti };
  }
  return { fwd, inv };
}

/** Smallest subdivision making every offset an integer count of sub-edges. The
 *  floor of 2 is what the vertex-link certificate needs (at N = 1 a single cube
 *  is too coarse for a vertex link to triangulate); H₁ is subdivision-invariant,
 *  so this never changes the homology. */
function chooseN(spec: SolidWorldSpec): number {
  for (let N = 2; N <= 24; N++) {
    let ok = true;
    for (const p of spec.pairings) {
      if (!p.offset) continue;
      for (const o of p.offset) if (Math.abs(o * N - Math.round(o * N)) > 1e-9) ok = false;
    }
    if (ok) return N;
  }
  throw new Error('offset denominator too large for the subdivision grid');
}

// ── the subdivided cubical complex, with gluing reduction ────────────────────
export interface Homology {
  /** Free rank of H₁ (the number of ℤ summands). */
  rank: number;
  /** Torsion invariant factors (> 1) of H₁, e.g. [2, 2] for (ℤ/2)². */
  torsion: number[];
  /** Pretty-printed H₁, e.g. "ℤ² ⊕ ℤ/2". */
  h1: string;
  /** Euler characteristic V − E + F − C; must be 0 for a closed 3-manifold. */
  euler: number;
  vertexClasses: number;
  edgeClasses: number;
  /** True iff every vertex link is a 2-sphere — the genuine manifold certificate. */
  manifold: boolean;
}

export function computeHomology(spec: SolidWorldSpec, N = chooseN(spec)): Homology {
  const { fwd, inv } = buildGens(spec);
  const gridToWorld = (g: V3): V3 => [-1 + (g[0] * EDGE_LEN) / N, -1 + (g[1] * EDGE_LEN) / N, -1 + (g[2] * EDGE_LEN) / N];
  const worldToGrid = (w: V3): V3 => [
    Math.round(((w[0] + 1) * N) / EDGE_LEN),
    Math.round(((w[1] + 1) * N) / EDGE_LEN),
    Math.round(((w[2] + 1) * N) / EDGE_LEN),
  ];

  // A cell is a list of its integer-grid corner points. Helpers derive its
  // spanning axes (which coordinates vary) and canonical min-corner.
  type Pt = V3;
  const axesOf = (corners: Pt[]): number[] => {
    const axes: number[] = [];
    for (let k = 0; k < 3; k++) {
      let lo = Infinity, hi = -Infinity;
      for (const c of corners) { lo = Math.min(lo, c[k]); hi = Math.max(hi, c[k]); }
      if (hi > lo) axes.push(k);
    }
    return axes;
  };
  const minCorner = (corners: Pt[]): V3 => {
    const m: V3 = [Infinity, Infinity, Infinity];
    for (const c of corners) for (let k = 0; k < 3; k++) m[k] = Math.min(m[k], c[k]);
    return m;
  };
  const cellKey = (corners: Pt[]): string => {
    const axes = axesOf(corners); const m = minCorner(corners);
    return `${axes.join('')}|${m[0]},${m[1]},${m[2]}`;
  };

  // Image axes of a signed-permutation M acting on a cell spanning `axes`, and
  // the orientation sign (det of M restricted to that tangent k-plane).
  const imageAxes = (M: M3, axes: number[]): number[] =>
    axes.map((d) => { for (let r = 0; r < 3; r++) if (Math.abs(M[r * 3 + d]) > 0.5) return r; return d; }).sort((a, b) => a - b);
  const orientSign = (M: M3, axes: number[]): number => {
    if (axes.length === 0) return 1;
    const img = imageAxes(M, axes);
    if (axes.length === 1) return Math.sign(M[img[0] * 3 + axes[0]]);
    // 2×2 determinant of the sub-block (rows = image axes, cols = source axes)
    const a = M[img[0] * 3 + axes[0]], b = M[img[0] * 3 + axes[1]];
    const c = M[img[1] * 3 + axes[0]], d = M[img[1] * 3 + axes[1]];
    return Math.sign(a * d - b * c);
  };

  const applyGen = (corners: Pt[], g: Gen): { corners: Pt[]; sign: number } => {
    const sign = orientSign(g.M, axesOf(corners));
    const out = corners.map((c) => {
      const w = applyM3(g.M, gridToWorld(c));
      return worldToGrid([w[0] + g.t[0], w[1] + g.t[1], w[2] + g.t[2]]);
    });
    return { corners: out, sign };
  };

  const inCube = (corners: Pt[]): boolean => corners.every((c) => c[0] >= 0 && c[0] <= N && c[1] >= 0 && c[1] <= N && c[2] >= 0 && c[2] <= N);
  const allGens = [...fwd, ...inv];

  /** Pull a cell back into the cube [0,N]³ by a breadth-first search over the
   *  deck group: apply generators until every corner is in range. Robust to the
   *  staggered side-pairings a screw produces (greedy face-crossing isn't). */
  const reduceToCube = (corners0: Pt[]): { corners: Pt[]; sign: number } => {
    if (inCube(corners0)) return { corners: corners0, sign: 1 };
    const seen = new Set<string>([cellKey(corners0)]);
    let frontier: { corners: Pt[]; sign: number }[] = [{ corners: corners0, sign: 1 }];
    for (let depth = 0; depth < 16 && seen.size < 20000; depth++) {
      const next: { corners: Pt[]; sign: number }[] = [];
      for (const node of frontier) for (const g of allGens) {
        const sign = node.sign * orientSign(g.M, axesOf(node.corners));
        const corners = node.corners.map((c) => {
          const w = applyM3(g.M, gridToWorld(c));
          return worldToGrid([w[0] + g.t[0], w[1] + g.t[1], w[2] + g.t[2]]);
        });
        if (inCube(corners)) return { corners, sign };
        const key = cellKey(corners);
        if (!seen.has(key)) { seen.add(key); next.push({ corners, sign }); }
      }
      frontier = next;
      if (frontier.length === 0) break;
    }
    throw new Error('cell reduction did not converge — check the gluing data');
  };

  // ── enumerate all cells of the subdivided cube, dense ids per dimension ─────
  const vId = new Map<string, number>(); // vertices keyed "x,y,z"
  const eKey = new Map<string, number>(); // edges keyed by cellKey
  const fKey = new Map<string, number>(); // faces (squares) keyed by cellKey
  const eCorners: Pt[][] = []; const fCorners: Pt[][] = [];

  const vKeyOf = (p: Pt) => `${p[0]},${p[1]},${p[2]}`;
  for (let x = 0; x <= N; x++) for (let y = 0; y <= N; y++) for (let z = 0; z <= N; z++) vId.set(vKeyOf([x, y, z]), vId.size);
  const edgeCorners = (d: number, m: V3): Pt[] => { const e: V3 = [0, 0, 0]; e[d] = 1; return [m, [m[0] + e[0], m[1] + e[1], m[2] + e[2]]]; };
  const faceCorners = (d: number, e: number, m: V3): Pt[] => {
    const ed: V3 = [0, 0, 0]; ed[d] = 1; const ee: V3 = [0, 0, 0]; ee[e] = 1;
    return [m, [m[0] + ed[0], m[1] + ed[1], m[2] + ed[2]], [m[0] + ed[0] + ee[0], m[1] + ed[1] + ee[1], m[2] + ed[2] + ee[2]], [m[0] + ee[0], m[1] + ee[1], m[2] + ee[2]]];
  };
  for (let d = 0; d < 3; d++) {
    for (let x = 0; x <= N; x++) for (let y = 0; y <= N; y++) for (let z = 0; z <= N; z++) {
      const m: V3 = [x, y, z]; if (m[d] >= N) continue; // edge must fit
      const cs = edgeCorners(d, m); eKey.set(cellKey(cs), eCorners.length); eCorners.push(cs);
    }
  }
  for (let d = 0; d < 3; d++) for (let e = d + 1; e < 3; e++) {
    for (let x = 0; x <= N; x++) for (let y = 0; y <= N; y++) for (let z = 0; z <= N; z++) {
      const m: V3 = [x, y, z]; if (m[d] >= N || m[e] >= N) continue;
      const cs = faceCorners(d, e, m); fKey.set(cellKey(cs), fCorners.length); fCorners.push(cs);
    }
  }
  const nVcells = vId.size, nEcells = eCorners.length, nFcells = fCorners.length;
  const nCubes = N * N * N;

  // ── identify boundary cells under each face-pairing (−axis face → image) ────
  const vUF = new UF(nVcells), eUF = new SignedUF(nEcells), fUF = new SignedUF(nFcells);
  const onMinusFace = (corners: Pt[], a: number) => corners.every((c) => c[a] === 0);

  for (let a = 0; a < 3; a++) {
    // vertices on the −a face
    for (let i = 0; i <= N; i++) for (let j = 0; j <= N; j++) {
      const p: V3 = [0, 0, 0]; p[a] = 0; p[(a + 1) % 3] = i; p[(a + 2) % 3] = j;
      const img = reduceToCube(applyGen([p], fwd[a]).corners).corners[0];
      vUF.union(vId.get(vKeyOf(p))!, vId.get(vKeyOf(img))!);
    }
    // edges on the −a face
    for (const [key, idx] of eKey) {
      const cs = eCorners[idx]; if (!onMinusFace(cs, a)) continue;
      const first = applyGen(cs, fwd[a]); const red = reduceToCube(first.corners);
      const sign = first.sign * red.sign; const tgt = eKey.get(cellKey(red.corners));
      if (tgt === undefined) throw new Error(`edge image left the cube: ${key}`);
      eUF.union(idx, tgt, sign);
    }
    // faces on the −a face
    for (const [key, idx] of fKey) {
      const cs = fCorners[idx]; if (!onMinusFace(cs, a)) continue;
      const first = applyGen(cs, fwd[a]); const red = reduceToCube(first.corners);
      const sign = first.sign * red.sign; const tgt = fKey.get(cellKey(red.corners));
      if (tgt === undefined) throw new Error(`face image left the cube: ${key}`);
      fUF.union(idx, tgt, sign);
    }
  }

  // ── class index maps ───────────────────────────────────────────────────────
  const vClass = new Map<number, number>();
  for (let i = 0; i < nVcells; i++) { const r = vUF.find(i); if (!vClass.has(r)) vClass.set(r, vClass.size); }
  const eClass = new Map<number, number>();
  for (let i = 0; i < nEcells; i++) { const r = eUF.find(i).root; if (!eClass.has(r)) eClass.set(r, eClass.size); }
  const fClass = new Map<number, number>();
  for (let i = 0; i < nFcells; i++) { const r = fUF.find(i).root; if (!fClass.has(r)) fClass.set(r, fClass.size); }
  const nV = vClass.size, nE = eClass.size, nF = fClass.size, nC = nCubes;

  const vClassOf = (p: Pt) => vClass.get(vUF.find(vId.get(vKeyOf(p))!))!;
  const eClassOf = (idx: number) => { const f = eUF.find(idx); return { id: eClass.get(f.root)!, sign: f.sign }; };

  // ── ∂₁ : edge-class → vertex-class (rep edge gives +head − tail) ────────────
  const d1: number[][] = Array.from({ length: nE }, () => new Array(nV).fill(0));
  for (const [root, id] of eClass) {
    const cs = eCorners[root]; const d = axesOf(cs)[0]; const m = minCorner(cs);
    const head: V3 = [...m]; head[d] += 1;
    d1[id][vClassOf(head)] += 1;
    d1[id][vClassOf(m)] -= 1;
  }

  // ── ∂₂ : face-class → edge-classes (oriented 4-cycle of the rep square) ─────
  const d2: number[][] = Array.from({ length: nF }, () => new Array(nE).fill(0));
  for (const [root, id] of fClass) {
    const cs = fCorners[root]; const [d, e] = axesOf(cs); const m = minCorner(cs);
    const ed: V3 = [0, 0, 0]; ed[d] = 1; const ee: V3 = [0, 0, 0]; ee[e] = 1;
    const add = (dir: number, base: V3, coeff: number) => {
      const idx = eKey.get(cellKey(edgeCorners(dir, base)))!; const ec = eClassOf(idx);
      d2[id][ec.id] += coeff * ec.sign;
    };
    add(d, m, +1);                                            // +d at m
    add(e, [m[0] + ed[0], m[1] + ed[1], m[2] + ed[2]], +1);   // +e at m+e_d
    add(d, [m[0] + ee[0], m[1] + ee[1], m[2] + ee[2]], -1);   // −d at m+e_e
    add(e, m, -1);                                            // −e at m
  }

  // self-check: ∂₂ then ∂₁ must vanish (catches any orientation/identification bug)
  for (let f = 0; f < nF; f++) {
    const acc = new Array(nV).fill(0);
    for (let edge = 0; edge < nE; edge++) if (d2[f][edge]) for (let v = 0; v < nV; v++) acc[v] += d2[f][edge] * d1[edge][v];
    if (acc.some((x) => x !== 0)) throw new Error('∂₂∘∂₁ ≠ 0 — orientation/gluing bug in homology');
  }

  const rank1 = smith(d1).length;
  const inv2 = smith(d2);
  const rank2 = inv2.length;
  const torsion = inv2.filter((x) => x > 1);
  const rank = nE - rank1 - rank2;
  const euler = nV - nE + nF - nC;

  // ── vertex-link manifold certificate: every link must be an S² ─────────────
  // Assemble each vertex's link around a single instance *in the cover*: the 8
  // unit cubes touching that instance (some are deck-translates of domain cubes,
  // reduced back). Each contributes a triangular link-face whose 3 link-vertices
  // are the incident edge-classes and 3 link-edges the incident face-classes. A
  // class is a manifold point iff its link is an S² (connected, χ = 2, every
  // link-edge shared by exactly two faces). Reading local faces by vertex-class
  // in the domain is wrong once a screw scatters the cubes — hence the cover.
  const edgeClassOfCell = (cs: V3[]): number => eClassOf(eKey.get(cellKey(reduceToCube(cs).corners))!).id;
  const faceClassOfCell = (cs: V3[]): number => fClass.get(fUF.find(fKey.get(cellKey(reduceToCube(cs).corners))!).root)!;
  const repVertex = new Map<number, V3>();
  for (let x = 0; x <= N; x++) for (let y = 0; y <= N; y++) for (let z = 0; z <= N; z++) {
    const p: V3 = [x, y, z]; const cls = vClassOf(p); if (!repVertex.has(cls)) repVertex.set(cls, p);
  }
  let manifold = true;
  for (const p of repVertex.values()) {
    const flist: { lv: number[]; le: number[] }[] = [];
    for (let dx = -1; dx <= 0; dx++) for (let dy = -1; dy <= 0; dy++) for (let dz = -1; dz <= 0; dz++) {
      const cm: V3 = [p[0] + dx, p[1] + dy, p[2] + dz]; // a unit cube with p as a corner
      const lv: number[] = [], le: number[] = [];
      for (let k = 0; k < 3; k++) {
        const em: V3 = [...p]; em[k] = cm[k];                 // cube edge along k at this corner
        lv.push(edgeClassOfCell(edgeCorners(k, em)));
        const j = (k + 1) % 3, l = (k + 2) % 3;               // cube face ⟂ k at this corner
        const fm: V3 = [...cm]; fm[k] = p[k];
        le.push(faceClassOfCell(faceCorners(Math.min(j, l), Math.max(j, l), fm)));
      }
      flist.push({ lv, le });
    }
    const Vs = new Set<number>(), Es = new Set<number>(); const inc = new Map<number, number>();
    for (const f of flist) { for (const v of f.lv) Vs.add(v); for (const e of f.le) { Es.add(e); inc.set(e, (inc.get(e) ?? 0) + 1); } }
    if (Vs.size - Es.size + flist.length !== 2) { manifold = false; break; }       // χ ≠ 2
    if ([...inc.values()].some((c) => c !== 2)) { manifold = false; break; }        // not closed
    const adj = new Map<number, number[]>(); flist.forEach((_, i) => adj.set(i, []));
    const byEdge = new Map<number, number[]>();
    flist.forEach((f, i) => f.le.forEach((e) => { const a = byEdge.get(e) ?? []; a.push(i); byEdge.set(e, a); }));
    for (const fs of byEdge.values()) if (fs.length === 2) { adj.get(fs[0])!.push(fs[1]); adj.get(fs[1])!.push(fs[0]); }
    const seen = new Set<number>([0]); const stack = [0];
    while (stack.length) { const a = stack.pop()!; for (const b of adj.get(a)!) if (!seen.has(b)) { seen.add(b); stack.push(b); } }
    if (seen.size !== flist.length) { manifold = false; break; }                    // disconnected link
  }

  return { rank, torsion, h1: formatH1(rank, torsion), euler, vertexClasses: nV, edgeClasses: nE, manifold };
}

function formatH1(rank: number, torsion: number[]): string {
  const parts: string[] = [];
  if (rank === 1) parts.push('ℤ');
  else if (rank > 1) parts.push(`ℤ${superscript(rank)}`);
  for (const d of torsion) parts.push(`ℤ/${d}`);
  return parts.length ? parts.join(' ⊕ ') : '0';
}

function superscript(n: number): string {
  const map: Record<string, string> = { '0': '⁰', '1': '¹', '2': '²', '3': '³', '4': '⁴', '5': '⁵', '6': '⁶', '7': '⁷', '8': '⁸', '9': '⁹' };
  return String(n).split('').map((c) => map[c] ?? c).join('');
}
